source "https://rubygems.org"

# Gemfile
gem "bcrypt", "~> 3.1.7"
gem "rails", "~> 8.0.1"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "kamal", require: false

gem "thruster", require: false


group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rubycritic", require: false
  gem "rubocop", require: false
  gem "simplecov", require: false
  gem "rubocop-rails", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "reek"
  gem "rspec-rails", "~> 6.1.0"
  gem "capybara"
  gem "cucumber-rails", require: false
  gem "database_cleaner"
  gem "selenium-webdriver"
end

group :development do
  gem "web-console"
  gem "rdoc"
end
