require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/coordenadors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Coordenador. As you add validations to Coordenador, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Coordenador.create! valid_attributes
      get coordenadors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      coordenador = Coordenador.create! valid_attributes
      get coordenador_url(coordenador)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_coordenador_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      coordenador = Coordenador.create! valid_attributes
      get edit_coordenador_url(coordenador)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Coordenador" do
        expect {
          post coordenadors_url, params: { coordenador: valid_attributes }
        }.to change(Coordenador, :count).by(1)
      end

      it "redirects to the created coordenador" do
        post coordenadors_url, params: { coordenador: valid_attributes }
        expect(response).to redirect_to(coordenador_url(Coordenador.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Coordenador" do
        expect {
          post coordenadors_url, params: { coordenador: invalid_attributes }
        }.to change(Coordenador, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post coordenadors_url, params: { coordenador: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested coordenador" do
        coordenador = Coordenador.create! valid_attributes
        patch coordenador_url(coordenador), params: { coordenador: new_attributes }
        coordenador.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the coordenador" do
        coordenador = Coordenador.create! valid_attributes
        patch coordenador_url(coordenador), params: { coordenador: new_attributes }
        coordenador.reload
        expect(response).to redirect_to(coordenador_url(coordenador))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        coordenador = Coordenador.create! valid_attributes
        patch coordenador_url(coordenador), params: { coordenador: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested coordenador" do
      coordenador = Coordenador.create! valid_attributes
      expect {
        delete coordenador_url(coordenador)
      }.to change(Coordenador, :count).by(-1)
    end

    it "redirects to the coordenadors list" do
      coordenador = Coordenador.create! valid_attributes
      delete coordenador_url(coordenador)
      expect(response).to redirect_to(coordenadors_url)
    end
  end
end
