require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/materia", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Materium. As you add validations to Materium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Materium.create! valid_attributes
      get materia_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      materium = Materium.create! valid_attributes
      get materium_url(materium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_materium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      materium = Materium.create! valid_attributes
      get edit_materium_url(materium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Materium" do
        expect {
          post materia_url, params: { materium: valid_attributes }
        }.to change(Materium, :count).by(1)
      end

      it "redirects to the created materium" do
        post materia_url, params: { materium: valid_attributes }
        expect(response).to redirect_to(materium_url(Materium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Materium" do
        expect {
          post materia_url, params: { materium: invalid_attributes }
        }.to change(Materium, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post materia_url, params: { materium: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested materium" do
        materium = Materium.create! valid_attributes
        patch materium_url(materium), params: { materium: new_attributes }
        materium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the materium" do
        materium = Materium.create! valid_attributes
        patch materium_url(materium), params: { materium: new_attributes }
        materium.reload
        expect(response).to redirect_to(materium_url(materium))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        materium = Materium.create! valid_attributes
        patch materium_url(materium), params: { materium: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested materium" do
      materium = Materium.create! valid_attributes
      expect {
        delete materium_url(materium)
      }.to change(Materium, :count).by(-1)
    end

    it "redirects to the materia list" do
      materium = Materium.create! valid_attributes
      delete materium_url(materium)
      expect(response).to redirect_to(materia_url)
    end
  end
end
